debug: No
me: 'paced'
desc: >
  This is a filehost running on the Python pipette module: a 
  fast, open-source, lightweight, scalable private filehost 
  developed by paced.
diag_desc: >
  Diagnostics/usage page for a filehost running on the Python 
  pipette module: a fast, open-source, lightweight, scalable 
  private filehost developed by paced.

upload_dir: 'pics'
apikey_file: 'api.keys'
db_file: 'pipette.db'
schema_file: 'schema.sql'
entropy: 64
extensions: 
  - "jpg"
  - "png"
  - "txt"
  - "mp4"
  - "webm"
  - "mp3"
  - "gif"
  - "bmp"

path_minlength 2
path_maxlength: 4

too_many_collisions: 100
