# Pipette Settings

WHOAMI: Anonymous

DEBUG: no  # Keep this as no as debug mode is a security risk.
STASH: yes  # Keep an archive of files after deleting them, or no?

BASE_DESCRIPTION: >
  "This is a filehost running on the Python pipette module: a fast,
  open-source, lightweight, scalable private filehost developed by paced."
DIAG_DESCRIPTION: >
  "Diagnostics/usage page for a filehost running on the Python pipette module:
  a fast, open-source, lightweight, scalable private filehost developed by
  paced."

ALLOWED_EXTENSIONS:
  - "jpg"
  - "png"
  - "txt"
  - "mp4"
  - "webm"
  - "mp3"
  - "gif"
  - "bmp"

PATH_MINLENGTH: 10
PATH_MAXLENGTH: 16
